# Site settings
title: Developer Blog!
email: nsipplswezey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blogging is a great way to think clearly
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nsipplswezey.github.io/" # the base hostname & protocol for your site
twitter_username: null
github_username:  nsipplswezey

# Build settings
markdown: kramdown
