# Site settings
title: Developer blogging for clear thinking!
email: nsipplswezey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where I stop to put down working ideas.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nsipplswezey.github.io/" # the base hostname & protocol for your site
twitter_username: null
github_username:  nsipplswezey

# Build settings
markdown: kramdown
